### ISSUE TITLE
noMocha have no effect?

### ISSUE THREAD

**Issue by simme** [bloglovin/lintlovin#11] opened 2015-02-25 09:51 UTC
I didn't not test this properly. But it seems like `noMocha` has no effect, it still expects a `test` directory to be around.

**Comment by voxpelli** [comment] 2015-04-06 12:20
I'm unable to reproduce this. Either with or without `noMocha` it never expects the `test` directory to be around. It do however expect `mocha` to be used _if_ a `test` directory is around and `noMocha` is used to tell it to not set up `mocha` tests when that's the case.

Closing for now. If we find out more details on this and can reproduce it then we can reopen it or start a new issue.

**Closed by voxpelli** 2015-04-06 12:20 UTC
Labels: bug
